"""
Tests for the analyze_news() function generated by the Ralph loop.

Mirrors the test suite in ralph_wiggum_technique.py:
  - Finance examples (is_finance=True): analyze_news() must return an object
    with 'sentiment' and 'impact_score' attributes.
  - Non-finance examples (is_finance=False): analyze_news() must raise an exception.

The generated module is loaded fresh for each test to avoid Python's module
cache returning a stale version across test runs.

Generated code is expected at: out/ralph/generated.py
"""

import importlib.util
import sys
from pathlib import Path

import pytest

GENERATED_PATH = Path("out/ralph/generated.py")  # must match GENERATED_FILE in ralph.sh

TEST_EXAMPLES = [
    # --- Finance (7) ---
    (
        "U.S. stocks closed higher on Tuesday, boosted by positive labor market reports, "
        "as the S&P 500 gained 1.2% and the Nasdaq rose 1.5%.",
        True,
    ),
    (
        "Netflix's planned $82.7 billion acquisition of Warner Bros. Discovery's studios "
        "and HBO Max is expected to close ahead of schedule in Q3 2026, shifting the "
        "landscape of streaming consolidation and media market caps.",
        True,
    ),
    (
        "Crude oil traded higher this morning, breaking the $71 per barrel mark, amid "
        "rising tensions between the U.S. and Iran ahead of nuclear talks in Geneva.",
        True,
    ),
    (
        "CoStar Group (CSGP) posted full-year 2025 results showing 19% revenue growth "
        "and announced a massive $700 million share repurchase program for 2026, "
        "signaling strong capital return for investors.",
        True,
    ),
    (
        "Apple (AAPL) reported record Q4 2025 earnings, with revenue up 12% year-over-year "
        "to $124 billion and EPS of $2.18, beating analyst estimates by 8 cents.",
        True,
    ),
    (
        "The Federal Reserve signaled a potential 25 basis point rate cut in Q2 2026 "
        "following lower-than-expected CPI data, sending Treasury yields lower and "
        "pushing equity markets to new highs.",
        True,
    ),
    (
        "Amazon (AMZN) announced a $2.5 billion acquisition of a leading AI healthcare "
        "startup, expanding its AWS cloud and enterprise health-services division.",
        True,
    ),
    # --- Non-finance (3) ---
    (
        "To make a traditional Beef Bourguignon, slowly braise a chuck roast in a "
        "full-bodied Pinot Noir with pearl onions, mushrooms, and thick-cut bacon. "
        "Let it simmer at 160°C for at least three hours until the meat is fork-tender.",
        False,
    ),
    (
        "The Golden State Warriors defeated the Boston Celtics 112-98 last night in a "
        "thrilling NBA playoff game, with Stephen Curry scoring 38 points and 9 assists.",
        False,
    ),
    (
        "Christopher Nolan's latest sci-fi epic received a standing ovation at the "
        "Cannes Film Festival, with critics praising its stunning practical effects "
        "and emotionally resonant screenplay.",
        False,
    ),
]


def load_analyze_news():
    """Load analyze_news() from the generated module, bypassing the module cache."""
    if not GENERATED_PATH.exists():
        pytest.skip(f"Generated file not found: {GENERATED_PATH}")

    spec = importlib.util.spec_from_file_location("generated", GENERATED_PATH)
    if spec is None or spec.loader is None:
        pytest.fail(f"importlib could not load {GENERATED_PATH}")

    module = importlib.util.module_from_spec(spec)
    sys.modules["generated"] = module
    spec.loader.exec_module(module)  # type: ignore[union-attr]

    analyze_news = getattr(module, "analyze_news", None)
    if analyze_news is None or not callable(analyze_news):
        pytest.fail("Generated module has no callable 'analyze_news' function.")

    return analyze_news


# Build parametrize IDs for readable output
_ids = [
    f"{'finance' if is_finance else 'non-finance'}-{i}"
    for i, (_, is_finance) in enumerate(TEST_EXAMPLES, 1)
]


@pytest.mark.parametrize("article,is_finance", TEST_EXAMPLES, ids=_ids)
def test_analyze_news(article, is_finance):
    analyze_news = load_analyze_news()

    if is_finance:
        # Finance: must return a structured object with sentiment and impact_score.
        result = analyze_news(article)
        assert hasattr(result, "sentiment"), (
            f"Finance result missing 'sentiment' attribute. Got: {result!r}"
        )
        assert hasattr(result, "impact_score"), (
            f"Finance result missing 'impact_score' attribute. Got: {result!r}"
        )
    else:
        # Non-finance: must raise an exception.
        with pytest.raises(Exception):
            analyze_news(article)
